services:
  rhapsody.commons.twig.rhapsody_extension:
    class: 'Rhapsody\CommonsBundle\Twig\Extension\RhapsodyExtension'
    tags:
      - { name: "twig.extension" }
      
  rhapsody.commons.twig.rhapsody_lipsum_extension:
    class: 'Rhapsody\CommonsBundle\Twig\Extension\RhapsodyLipsumExtension'
    tags:
      - { name: "twig.extension" }

  rhapsody.commons.twig.rhapsody_routing_extension:
    class: 'Rhapsody\CommonsBundle\Twig\Extension\RhapsodyRoutingExtension'
    arguments: ["@service_container", "@router"]
    tags:
      - { name: "twig.extension" }
      
  rhapsody.commons.twig.extension.markdown_extension:
    class: 'Rhapsody\CommonsBundle\Twig\Extension\RhapsodyMarkdownExtension'
    tags:
      - { name: "twig.extension" }